import { StrictMode } from 'react'
import { createRoot } from 'react-dom/client'
import './index.css'
import App from './App.jsx'

createRoot(document.getElementById('root')).render(
  <StrictMode>
    <App />
  </StrictMode>,
)

// ── PWA Service Worker Registration ──────────────────────────────────────────
// Registers the Workbox service worker generated by vite-plugin-pwa.
// This enables: offline support, caching, and "Add to Home Screen" on mobile.
if ('serviceWorker' in navigator && import.meta.env.PROD) {
  import('virtual:pwa-register').then(({ registerSW }) => {
    registerSW({
      // Auto-update when a new version is deployed
      onNeedRefresh() {
        // Show a toast or banner prompting user to refresh
        if (window.confirm('StockMind AI has been updated! Reload to get the latest version?')) {
          window.location.reload()
        }
      },
      onOfflineReady() {
        console.log('[PWA] App is ready to work offline')
      },
      onRegistered(r) {
        // Check for updates every hour
        r && setInterval(() => r.update(), 60 * 60 * 1000)
      },
    })
  }).catch(() => {
    // PWA not available in dev — that's fine
  })
}
